# Generated by Django 4.2.11 on 2025-11-06 07:08

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt",
            field=models.FileField(
                help_text="Payment receipt (max 10MB, JPG/PNG/PDF)",
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_payment_receipt],
            ),
        ),
    ]
