# Generated by Django 4.2.11 on 2025-11-06 07:08

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorapplication",
            name="certificates",
            field=models.FileField(
                blank=True,
                help_text="Certificates (max 5MB, PDF/JPG/PNG)",
                null=True,
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_instructor_certificate],
            ),
        ),
        migrations.AlterField(
            model_name="instructorapplication",
            name="resume",
            field=models.FileField(
                blank=True,
                help_text="Resume/CV (max 5MB, PDF/DOC/DOCX)",
                null=True,
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_instructor_resume],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture (max 5MB, JPG/PNG, will be optimized)",
                null=True,
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_profile_picture],
            ),
        ),
    ]
