# Generated by Django 4.2.11 on 2025-11-06 07:56

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_instructorapplication_certificates_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorapplication",
            name="certificates",
            field=models.FileField(
                blank=True,
                help_text="Combined certificates/degrees in one PDF (max 10MB, PDF only)",
                null=True,
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_instructor_certificate],
            ),
        ),
        migrations.AlterField(
            model_name="instructorapplication",
            name="motivation",
            field=models.TextField(
                blank=True,
                help_text="Why do you want to become an instructor? (Optional)",
                null=True,
            ),
        ),
    ]
