# Generated by Django 4.2.11 on 2025-11-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Pyinnya Hub", max_length=100)),
                (
                    "site_name_burmese",
                    models.CharField(
                        default="ပညာဟပ်",
                        max_length=100,
                        verbose_name="Site Name (Burmese)",
                    ),
                ),
                (
                    "menu_dashboard",
                    models.CharField(default="Dashboard", max_length=50),
                ),
                ("menu_courses", models.CharField(default="Courses", max_length=50)),
                (
                    "menu_my_courses",
                    models.CharField(default="My Courses", max_length=50),
                ),
                ("menu_payments", models.CharField(default="Payments", max_length=50)),
                ("menu_profile", models.CharField(default="Profile", max_length=50)),
                ("menu_logout", models.CharField(default="Log out", max_length=50)),
                ("menu_login", models.CharField(default="Login", max_length=50)),
                ("menu_register", models.CharField(default="Register", max_length=50)),
                (
                    "notif_payment_pending",
                    models.TextField(
                        default="ငွေပေးချေမှု အောင်မြင်စွာ တင်သွင်းပြီးပါပြီ။ Admin မှ အတည်ပြုပေးမည်ဖြစ်ပါသည်။",
                        help_text="Message shown when payment is submitted",
                        verbose_name="Payment Pending Message",
                    ),
                ),
                (
                    "notif_payment_approved",
                    models.TextField(
                        default="ငွေပေးချေမှု အတည်ပြုပြီးပါပြီ။ သင်ခန်းစာကို စတင်နိုင်ပါပြီ။",
                        help_text="Message shown when payment is approved",
                        verbose_name="Payment Approved Message",
                    ),
                ),
                (
                    "notif_payment_rejected",
                    models.TextField(
                        default="ငွေပေးချေမှု ငြင်းပယ်ခံရပါသည်။ ကျေးဇူးပြု၍ ပြန်လည်စစ်ဆေးပြီး ထပ်မံတင်သွင်းပေးပါ။",
                        help_text="Message shown when payment is rejected",
                        verbose_name="Payment Rejected Message",
                    ),
                ),
                (
                    "notif_course_enrolled",
                    models.TextField(
                        default="သင်ခန်းစာတွင် အောင်မြင်စွာ စာရင်းသွင်းပြီးပါပြီ။",
                        help_text="Message shown when successfully enrolled in course",
                        verbose_name="Course Enrolled Message",
                    ),
                ),
                (
                    "notif_course_approved",
                    models.TextField(
                        default="သင်ခန်းစာကို အတည်ပြုပြီးပါပြီ။ ယခု ထုတ်ဝေနိုင်ပါပြီ။",
                        help_text="Message shown when course is approved by admin",
                        verbose_name="Course Approved Message",
                    ),
                ),
                (
                    "notif_course_rejected",
                    models.TextField(
                        default="သင်ခန်းစာ ငြင်းပယ်ခံရပါသည်။ ကျေးဇူးပြု၍ ပြင်ဆင်ပြီး ထပ်မံတင်သွင်းပေးပါ။",
                        help_text="Message shown when course is rejected",
                        verbose_name="Course Rejected Message",
                    ),
                ),
                (
                    "notif_welcome",
                    models.TextField(
                        default="Pyinnya Hub မှ ကြိုဆိုပါသည်။ စာရင်းသွင်းမှု အောင်မြင်ပါသည်။",
                        help_text="Message shown after successful registration",
                        verbose_name="Welcome Message",
                    ),
                ),
                (
                    "notif_already_enrolled",
                    models.TextField(
                        default="သင့်တွင် ဤသင်ခန်းစာ ရှိပြီးဖြစ်ပါသည်။",
                        help_text="Message shown when user already enrolled",
                        verbose_name="Already Enrolled Message",
                    ),
                ),
                (
                    "notif_access_denied",
                    models.TextField(
                        default="ဝင်ခွင့်မရှိပါ။",
                        help_text="Message shown when access is denied",
                        verbose_name="Access Denied Message",
                    ),
                ),
                (
                    "default_theme",
                    models.CharField(
                        choices=[("light", "Light Mode"), ("dark", "Dark Mode")],
                        default="light",
                        help_text="Default theme for new users",
                        max_length=10,
                    ),
                ),
                (
                    "allow_theme_toggle",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to toggle between light and dark mode",
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        default="admin@pyinnyahub.com",
                        help_text="Email address for admin notifications",
                        max_length=254,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@pyinnyahub.com",
                        help_text="Email address for user support",
                        max_length=254,
                    ),
                ),
                (
                    "enable_payment_upload",
                    models.BooleanField(
                        default=True, help_text="Enable manual payment upload"
                    ),
                ),
                (
                    "enable_course_reviews",
                    models.BooleanField(
                        default=True, help_text="Enable course reviews and ratings"
                    ),
                ),
                (
                    "enable_instructor_applications",
                    models.BooleanField(
                        default=True, help_text="Enable instructor applications"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
