# Generated by Django 4.2.11 on 2025-11-06 07:08

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0002_initial"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="allow_attachment_download",
            field=models.BooleanField(
                default=True, help_text="Allow students to download attachments"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="allow_video_download",
            field=models.BooleanField(
                default=False, help_text="Allow students to download video file"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Admin approved this lesson content"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="requires_approval",
            field=models.BooleanField(
                default=True,
                help_text="This lesson requires admin approval before publishing",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="promo_video",
            field=models.FileField(
                blank=True,
                help_text="Promotional video (max 500MB, MP4/WEBM)",
                null=True,
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_lesson_video],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                help_text="Course thumbnail image (min 800x450px, max 5MB, will be optimized)",
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_course_thumbnail],
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Upload video file (max 500MB, MP4/WEBM/MOV)",
                null=True,
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_lesson_video],
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="External video URL (YouTube, Vimeo, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lessonattachment",
            name="file",
            field=models.FileField(
                help_text="Lesson attachment (max 50MB, PDF/DOC/PPT/ZIP)",
                upload_to=core.utils.generate_unique_filename,
                validators=[core.utils.validate_lesson_attachment],
            ),
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_spent_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total time spent on this lesson in seconds",
                    ),
                ),
                (
                    "last_position_seconds",
                    models.PositiveIntegerField(
                        default=0, help_text="Last video position for resume"
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="courses.lesson",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Progress",
                "verbose_name_plural": "Lesson Progress Records",
                "db_table": "lesson_progress",
                "ordering": ["-last_viewed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_completed"],
                        name="lesson_prog_user_id_247085_idx",
                    ),
                    models.Index(
                        fields=["lesson", "is_completed"],
                        name="lesson_prog_lesson__7f1273_idx",
                    ),
                ],
                "unique_together": {("user", "lesson")},
            },
        ),
    ]
