# Generated by Django 4.2.11 on 2025-11-06 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0002_initial"),
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutbatch",
            name="processed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"role": "instructor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payouts",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["instructor", "status"], name="payouts_instruc_5ea50b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["status", "created_at"], name="payouts_status_ef59be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["course", "status"], name="payouts_course__387d68_idx"
            ),
        ),
    ]
