# Generated by Django 4.2.11 on 2025-11-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_type', models.CharField(blank=True, help_text='Type of email (registration, payment_approved, etc.)', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('registration', 'Registration'), ('instructor_application', 'Instructor Application'), ('payment', 'Payment'), ('course', 'Course'), ('subscription', 'Subscription'), ('payout', 'Payout'), ('system', 'System')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_via_email', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('registration', 'User Registration'), ('instructor_approved', 'Instructor Application Approved'), ('instructor_rejected', 'Instructor Application Rejected'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('course_approved', 'Course Approved'), ('course_rejected', 'Course Rejected'), ('subscription_expiry_reminder', 'Subscription Expiry Reminder'), ('subscription_expired', 'Subscription Expired'), ('payout_completed', 'Payout Completed'), ('payout_cancelled', 'Payout Cancelled'), ('password_reset', 'Password Reset')], help_text='Notification event type', max_length=50, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable/disable this notification')),
                ('send_email', models.BooleanField(default=True, help_text='Send notification via email')),
                ('send_in_app', models.BooleanField(default=True, help_text='Send notification as in-app notification')),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_settings',
            },
        ),
    ]
